<?php
require_once(dirname(dirname(__FILE__)).DIRECTORY_SEPARATOR."init.php");
require_once(INC_DIR.DIRECTORY_SEPARATOR."Cache.class.php");
require_once(INC_DIR.DIRECTORY_SEPARATOR."System.class.php");
require_once(ROOT_DIR.'/vendor/autoload.php');
require_once("FileAPICommand.class.php");

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Cell\AdvancedValueBinder;

class FileAPISurTrackingXlsxExportCommand extends FileAPICommand {

    /**
     * 將 Spreadsheet 物件寫入到匯出目錄的暫存檔案
     * @param Spreadsheet $spreadsheet PhpSpreadsheet 物件
     * @param string $filename 檔案名稱
     */
    private function write_export_tmp_file(&$spreadsheet, $filename = 'tmp.xlsx') {
        // 也複製一份到匯出資料夾
        $writer = new Xlsx($spreadsheet);
        $writer->save(EXPORT_DIR.DIRECTORY_SEPARATOR.$filename);
        //zipExports(); // 註解掉，如果需要打包功能可啟用
    }

    /**
     * 將 Spreadsheet 物件直接輸出到 PHP 輸出流供瀏覽器下載
     * @param Spreadsheet $spreadsheet PhpSpreadsheet 物件
     * @param string $filename 檔案名稱
     */
    private function write_php_output(&$spreadsheet, $filename = 'tmp.xlsx') {
        // 清除所有緩衝區的內容，並關閉輸出緩衝
        // 注意: 如果之前有其他輸出緩衝內容，此操作會清除它們
        ob_end_clean();

        // 設定 HTTP Header 告知瀏覽器這是 XLSX 檔案並強制下載
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="'.$filename.'"');
        header('Cache-Control: max-age=0');
        header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');
        header ('Cache-Control: cache, must-revalidate');
        header ('Pragma: public');

        // 建立寫入器並將內容保存到 PHP 輸出流
        $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
        $writer->save('php://output');
    }

    /**
     * 執行 Excel 匯出操作，設定元資料並輸出檔案
     * @param Spreadsheet $spreadsheet PhpSpreadsheet 物件
     * @param array $params 包含匯出所需參數的陣列
     * @param string $title 匯出檔案的標題
     */
    private function export(&$spreadsheet, &$params, $title) {
        // 設定 Excel 檔案的元資料
        $spreadsheet->getProperties()
            ->setCreator("地政智慧控管系統")
            ->setLastModifiedBy("地政智慧控管系統")
            ->setTitle("$title 匯出")
            ->setSubject("$title 匯出")
            ->setDescription(
                "document for Office 2007 XLSX, generated by PHPSpreadsheet classes."
            )
            ->setKeywords("office 2007 openxml php xlsx")
            ->setCategory("export");

        // 根據 site 參數設定檔案名稱
        $filename = strtoupper($params['site']).'.xlsx';
        Logger::getInstance()->info('寫入 '.$filename);
        // 將檔案寫入到伺服器暫存目錄
        $this->write_export_tmp_file($spreadsheet, $filename);
        Logger::getInstance()->info('輸出 RESPONSE STREAM ... ');
        // 將檔案輸出到瀏覽器
        $this->write_php_output($spreadsheet, $filename);
        Logger::getInstance()->info('輸出 RESPONSE STREAM 完成');
    }

    /**
     * 為指定儲存格或範圍設定細邊框
     * @param \PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $worksheet 工作表物件
     * @param string $from 起始儲存格名稱 (e.g., 'A1')
     * @param string|null $to 結束儲存格名稱 (e.g., 'B2')，如果為 null 則表示單一儲存格
     */
    private function style_cell_border(&$worksheet, $from, $to = null) {
        $to = $to ?? $from; // 如果 $to 為空，則設定為 $from (單一儲存格)
        $worksheet->getStyle($from.':'.$to)->getBorders()->getTop()->setBorderStyle(Border::BORDER_THIN);
        $worksheet->getStyle($from.':'.$to)->getBorders()->getBottom()->setBorderStyle(Border::BORDER_THIN);
        $worksheet->getStyle($from.':'.$to)->getBorders()->getLeft()->setBorderStyle(Border::BORDER_THIN);
        $worksheet->getStyle($from.':'.$to)->getBorders()->getRight()->setBorderStyle(Border::BORDER_THIN);
    }

    /**
     * 為指定列的 A 到 J 欄位設定邊框
     * @param \PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $worksheet 工作表物件
     * @param int $row_num 列號
     */
    private function style_row_border(&$worksheet, $row_num) {
        foreach (range('A', 'J') as $column){
            $this->style_cell_border($worksheet, $column.$row_num);
        }
    }

    /**
     * 寫入測量案件追蹤資料到 XLSX 檔案
     * @param array $params 包含資料列、站點和標頭的陣列
     * @param string $title 匯出檔案的標題
     */
    private function write_sur_tracking_xlsx(&$params, $title) {
        $count = count($params['rows']);
        Logger::getInstance()->info('查到 '.$count.' 筆資料');

        // 構建模板檔案路徑
        $tpl = ROOT_DIR.DIRECTORY_SEPARATOR.'assets'.DIRECTORY_SEPARATOR.'xlsx'.DIRECTORY_SEPARATOR.'sur_tracking.tpl.xlsx';
        Logger::getInstance()->info('讀取 '.$tpl.' 樣板XLSX');

        // 載入 Excel 模板
        $spreadsheet = IOFactory::load($tpl);
        $worksheet = $spreadsheet->getActiveSheet();
        // 設定凍結窗格：凍結第二列 (標題列)，這樣 A3 以下的內容滾動時，第1和第2列會保持可見
        $worksheet->freezePane('A3');
        // 設定辦公室名稱
        $site = $params['site'];
        switch ($params['site']) {
            case 'HA': $site = '桃園'; break;
            case 'HB': $site = '中壢'; break;
            case 'HC': $site = '大溪'; break;
            case 'HD': $site = '楊梅'; break;
            case 'HE': $site = '蘆竹'; break;
            case 'HF': $site = '八德'; break;
            case 'HG': $site = '平鎮'; break;
            case 'HH': $site = '龜山'; break;
        }
        // $worksheet->setCellValueExplicit(
        //     'A1',
        //     '桃園市'.$site.'地政事務所',
        //     DataType::TYPE_STRING
        // );
        // 設定額外標頭
        if (!empty($params['header'])) {
            $worksheet->setCellValueExplicit(
                'A1',
                $site.'所 '.$params['header'],
                DataType::TYPE_STRING
            );
        }
        // 產製時間在 J1 欄位
        $worksheet->getStyle('J1')->getAlignment()->setWrapText(false);
        $worksheet->getStyle('J1')->getFont()->setName('標楷體'); // 設定字體
        $worksheet->getStyle('J1')->getFont()->setSize(12); // 設定字體大小
        $worksheet->getStyle('J1')->getAlignment()->setVertical(Alignment::VERTICAL_CENTER); // 垂直置中
        $worksheet->setCellValueExplicit(
            'J1', // 產製時間在 J1 欄位
            '產製日期：' . (date('Y') - 1911) . date('/m/d'), // 轉換為民國年
            DataType::TYPE_STRING
        );
        // 設定資料範圍的樣式：文字換行、字體、字體大小、垂直置中
        // 這是解決樣式跑掉的關鍵部分
        $data_end_row = $count + 3; // 資料從第 3 列開始，加上資料筆數
        $range_head = 'A3:J';
        $range = $range_head.$data_end_row;
        $worksheet->getStyle($range)->getAlignment()->setWrapText(true);
        // $worksheet->getStyle('$range)->getFont()->setName('微軟正黑體'); // 設定字體
        $worksheet->getStyle($range)->getFont()->setSize(12); // 設定字體大小
        $worksheet->getStyle($range)->getAlignment()->setVertical(Alignment::VERTICAL_CENTER); // 垂直置中

        /** JSON 資料範例
         * 收件年: '114',
         * 收件字: '桃Ｏ建',
         * 收件號: '007600',
         * 複丈原因: '鑑界',
         * 收件日期: '114-03-12',
         * 複丈日期: '114-08-04',
         * 逾期日期: '114-08-01',
         * 測量員: '江ＯＯ',,
         * 處理情形: { // 這裡假設是一個包含布林值的物件
         *  複核中": true,
         *  函詢他機關: false,
         *  召開會議會勘: false,
         *  延期複丈: false,
         *  補正、駁回: true
         * }
         */
        $row_num = 0;
        foreach( $params['rows'] as $index => $row ) {
            $row_num = $index + 3; // 模板有標頭和標題列 (1-2)，所以資料從第 3 列開始
            
            // 寫入各欄位資料，並明確指定為字串類型
            $worksheet->setCellValueExplicit('A'.$row_num, $row['收件年'], DataType::TYPE_STRING);
            $worksheet->setCellValueExplicit('B'.$row_num, $row['收件字'], DataType::TYPE_STRING);
            $worksheet->setCellValueExplicit('C'.$row_num, $row['收件號'], DataType::TYPE_STRING);
            $worksheet->setCellValueExplicit('D'.$row_num, $row['複丈原因'], DataType::TYPE_STRING);
            $worksheet->setCellValueExplicit('E'.$row_num, $row['收件日期'], DataType::TYPE_STRING);
            $worksheet->setCellValueExplicit('F'.$row_num, $row['複丈日期'], DataType::TYPE_STRING);
            $worksheet->setCellValueExplicit('G'.$row_num, $row['逾期日期'], DataType::TYPE_STRING);
            $worksheet->setCellValueExplicit('H'.$row_num, $row['測量員'], DataType::TYPE_STRING);
            $worksheet->setCellValueExplicit('I'.$row_num, $row['處理情形'], DataType::TYPE_STRING);
            $worksheet->setCellValueExplicit('J'.$row_num, $row['核章欄'], DataType::TYPE_STRING);
                        // 處理「處理情形」欄位，動態生成帶有核選框的文字
            $processingStatusText = '';
            $processingStatusData = $row['處理情形'] ?? []; // 確保存在
            
            // 使用 Unicode 核選框符號: ☐ (未選), ☑ (已選)
            $processingStatusText .= ($processingStatusData['複核中'] ?? false ? '☑' : '☐') . '複核中       ';
            $processingStatusText .= ($processingStatusData['函詢他機關'] ?? false ? '☑' : '☐') . '函詢他機關' . "\n";
            $processingStatusText .= ($processingStatusData['召開會議會勘'] ?? false ? '☑' : '☐') . '召開會議會勘 ';
            $processingStatusText .= ($processingStatusData['延期複丈'] ?? false ? '☑' : '☐') . '延期複丈' . "\n";
            $processingStatusText .= ($processingStatusData['補正、駁回'] ?? false ? '☑' : '☐') . '補正、駁回'; // 最後一項不加換行

            $worksheet->setCellValueExplicit(
                'I'.$row_num, // 假設 I 欄是「處理情形」
                $processingStatusText,
                DataType::TYPE_STRING
            );
            
            // 處理「核章欄」
            $worksheet->setCellValueExplicit('J'.$row_num, $row['核章欄'] ?? '', DataType::TYPE_STRING); // 假設 J 欄是「核章欄」
            
            // 為當前列設定邊框
            $this->style_row_border($worksheet, $row_num);
            
            // 設定行高自動調整以適應內容
            $worksheet->getRowDimension($row_num)->setRowHeight(-1);
        }

        // 寫入最後的簽章列
        $row_num += 1;
        $worksheet->mergeCells('A'.$row_num.':'.'J'.$row_num); // 合併儲存格
        $worksheet->setCellValueExplicit(
            'A'.$row_num,
            '檢查員                        '.
            '測量課長                      '.
            '秘書                          '.
            '主任                          ',
            DataType::TYPE_STRING
        );
        $worksheet->getRowDimension($row_num)->setRowHeight(45); // 設定簽章列的固定行高
        $worksheet->getStyle('A'.$row_num)->getFont()->setSize(16); // 設定字體大小
        $worksheet->getStyle('A'.$row_num)
            ->getAlignment()->setHorizontal(Alignment::HORIZONTAL_JUSTIFY)
            ->setVertical(Alignment::VERTICAL_CENTER); // 垂直置中

        // 執行最終的匯出和輸出
        $this->export($spreadsheet, $params, $title);
    }

    /**
     * 建構子：設定 PhpSpreadsheet 的值綁定器
     */
    function __construct() {
        // 設定 AdvancedValueBinder，使其在儲存格中遇到換行符號時自動啟用「文字換行」
        \PhpOffice\PhpSpreadsheet\Cell\Cell::setValueBinder( new AdvancedValueBinder() );
    }

    /**
     * 解構子 (目前為空)
     */
    function __destruct() {}

    /**
     * 執行命令的核心方法
     */
    public function execute() {
        // 匯出檔案的標題
        $title = '測量案件催辦單';
        Logger::getInstance()->info($title);
        // Logger::getInstance()->info(print_r($_POST, true)); // 除錯用，可視情況啟用

        // 從 $_POST 獲取輸入參數
        // 建議: 在實際應用中，應對 $_POST 數據進行更嚴格的驗證和淨化
        $params = array(
            "rows" => $_POST['jsons'] ?? [], // 使用 null 合併運算符提供預設空陣列
            "site" => $_POST['site'] ?? '',
            "header" => $_POST['header'] ?? ''
        );
        
        // 執行資料寫入和匯出流程
        $this->write_sur_tracking_xlsx($params, $title);
    }
}
